package org.kapit.peopledirectory;

import org.kapit.peopledirectory.dao.CompanyDAO;
import org.kapit.peopledirectory.dao.UserDAO;
import org.kapit.peopledirectory.dao.impl.CompanyDAOImpl;
import org.kapit.peopledirectory.dao.impl.UserDAOImpl;
import org.kapit.peopledirectory.model.Company;
import org.kapit.peopledirectory.model.Department;
import org.kapit.peopledirectory.model.Employee;
import org.kapit.peopledirectory.model.User;

import java.util.ArrayList;
import java.util.List;

public class DataGenerator {

    public static void main(String[] args) {

        addAdminUser();

        initData();

    }

    private static void initData() {

        System.out.println("...init data");
        Employee emp1 = new Employee(1, "Davis");
        Employee emp2 = new Employee(2, "Dexter");
        Employee emp3 = new Employee(3, "Grant");
        Employee emp4 = new Employee(4, "John");
        Employee emp5 = new Employee(5, "Griffith");
        Employee emp6 = new Employee(6, "Keith");
        Employee emp7 = new Employee(7, "Hashim");
        Employee emp8 = new Employee(8, "Hoyt");
        Employee emp9 = new Employee(9, "Jasper");
        Employee emp10 = new Employee(10, "Finn");
        Employee emp11 = new Employee(11, "Conan");
        Employee emp12 = new Employee(12, "Baxter");
        Employee emp13 = new Employee(13, "Stephen");
        Employee emp14 = new Employee(14, "Merrill");
        Employee emp15 = new Employee(15, "Lev");
        Employee emp16 = new Employee(16, "Yoshio");
        Employee emp17 = new Employee(17, "Xenos");
        Employee emp18 = new Employee(18, "Galvin");
        Employee emp19 = new Employee(19, "Walter");
        Employee emp20 = new Employee(20, "Carlos");
        Employee emp21 = new Employee(21, "Garrison");
        Employee emp22 = new Employee(22, "Kenneth");
        Employee emp23 = new Employee(23, "Lane");
        Employee emp24 = new Employee(24, "Chadwick");
        Employee emp25 = new Employee(25, "Garrison");
        Employee emp26 = new Employee(26, "Ethan");
        Employee emp27 = new Employee(27, "Joshua");
        Employee emp28 = new Employee(28, "Quinlan");
        Employee emp29 = new Employee(29, "Phelan");
        Employee emp30 = new Employee(30, "Ivan");
        Employee emp31 = new Employee(31, "Vernon");
        Employee emp32 = new Employee(32, "Leonard");
        Employee emp33 = new Employee(33, "Barclay");
        Employee emp34 = new Employee(34, "Damian");
        Employee emp35 = new Employee(35, "Dalton");
        Employee emp36 = new Employee(36, "Joel");
        Employee emp37 = new Employee(37, "Phillip");
        Employee emp38 = new Employee(38, "Leonard");
        Employee emp39 = new Employee(39, "Beck");
        Employee emp40 = new Employee(40, "Vladimir");
        Employee emp41 = new Employee(41, "Zeus");
        Employee emp42 = new Employee(42, "Leroy");
        Employee emp43 = new Employee(43, "Benedict");
        Employee emp44 = new Employee(44, "Alexander");
        Employee emp45 = new Employee(45, "Malachi");
        Employee emp46 = new Employee(46, "Damon");
        Employee emp47 = new Employee(47, "Adrian");
        Employee emp48 = new Employee(48, "Zeph");
        Employee emp49 = new Employee(49, "Wing");
        Employee emp50 = new Employee(50, "Andrew");
        Employee emp51 = new Employee(51, "Gavin");
        Employee emp52 = new Employee(52, "Tucker");
        Employee emp53 = new Employee(53, "Philip");
        Employee emp54 = new Employee(54, "Luke");
        Employee emp55 = new Employee(55, "Vaughan");
        Employee emp56 = new Employee(56, "Malik");
        Employee emp57 = new Employee(57, "Alden");
        Employee emp58 = new Employee(58, "Cruz");
        Employee emp59 = new Employee(59, "Driscoll");
        Employee emp60 = new Employee(60, "Gil");
        Employee emp61 = new Employee(61, "Jerry");
        Employee emp62 = new Employee(62, "Porter");
        Employee emp63 = new Employee(63, "Abel");
        Employee emp64 = new Employee(64, "Addison");
        Employee emp65 = new Employee(65, "Igor");
        Employee emp66 = new Employee(66, "Graiden");
        Employee emp67 = new Employee(67, "Griffith");
        Employee emp68 = new Employee(68, "Brandon");
        Employee emp69 = new Employee(69, "Ryan");
        Employee emp70 = new Employee(70, "Jackson");
        Employee emp71 = new Employee(71, "Chadwick");
        Employee emp72 = new Employee(72, "Kirk");
        Employee emp73 = new Employee(73, "Jared");
        Employee emp74 = new Employee(74, "Randall");
        Employee emp75 = new Employee(75, "Noah");
        Employee emp76 = new Employee(76, "Cade");
        Employee emp77 = new Employee(77, "Denton");
        Employee emp78 = new Employee(78, "Dominic");
        Employee emp79 = new Employee(79, "Malcolm");
        Employee emp80 = new Employee(80, "Jason");
        Employee emp81 = new Employee(81, "Dustin");
        Employee emp82 = new Employee(82, "Brock");
        Employee emp83 = new Employee(83, "Ferris");
        Employee emp84 = new Employee(84, "Steel");
        Employee emp85 = new Employee(85, "Chancellor");
        Employee emp86 = new Employee(86, "Jerome");
        Employee emp87 = new Employee(87, "Neville");
        Employee emp88 = new Employee(88, "Brock");
        Employee emp89 = new Employee(89, "Nathaniel");
        Employee emp90 = new Employee(90, "Wyatt");
        Employee emp91 = new Employee(91, "Ferris");
        Employee emp92 = new Employee(92, "Duncan");
        Employee emp93 = new Employee(93, "Caleb");
        Employee emp94 = new Employee(94, "Melvin");
        Employee emp95 = new Employee(95, "Kadeem");
        Employee emp96 = new Employee(96, "Avram");
        Employee emp97 = new Employee(97, "Eric");
        Employee emp98 = new Employee(98, "Lyle");
        Employee emp99 = new Employee(99, "Gil");
        Employee emp100 = new Employee(100, "Rigel");

        List employees1 = new ArrayList();
        employees1.add(emp1);
        employees1.add(emp2);
        employees1.add(emp3);
        employees1.add(emp4);
        employees1.add(emp5);
        employees1.add(emp6);
        employees1.add(emp7);
        employees1.add(emp8);
        employees1.add(emp9);
        employees1.add(emp10);
        employees1.add(emp11);
        employees1.add(emp12);
        employees1.add(emp13);
        employees1.add(emp14);
        employees1.add(emp15);
        employees1.add(emp16);
        employees1.add(emp17);
        employees1.add(emp18);
        employees1.add(emp19);
        employees1.add(emp20);
        employees1.add(emp61);
        employees1.add(emp62);
        employees1.add(emp63);
        employees1.add(emp64);
        employees1.add(emp65);
        employees1.add(emp66);
        employees1.add(emp67);
        employees1.add(emp68);
        employees1.add(emp69);
        employees1.add(emp70);
        employees1.add(emp71);
        employees1.add(emp72);
        employees1.add(emp73);
        employees1.add(emp74);
        employees1.add(emp75);
        employees1.add(emp76);
        employees1.add(emp77);
        employees1.add(emp78);
        employees1.add(emp79);
        employees1.add(emp80);
        employees1.add(emp81);
        employees1.add(emp82);
        employees1.add(emp83);
        employees1.add(emp84);
        employees1.add(emp85);
        employees1.add(emp86);
        employees1.add(emp87);
        employees1.add(emp88);
        employees1.add(emp89);
        employees1.add(emp90);
        employees1.add(emp91);
        employees1.add(emp92);
        employees1.add(emp93);
        employees1.add(emp94);
        employees1.add(emp95);
        employees1.add(emp96);
        employees1.add(emp97);
        employees1.add(emp98);
        employees1.add(emp99);
        employees1.add(emp100);
        List employees2 = new ArrayList();
        employees2.add(emp4);
        employees2.add(emp5);
        employees2.add(emp21);
        employees2.add(emp22);
        employees2.add(emp23);
        employees2.add(emp24);
        employees2.add(emp25);
        employees2.add(emp26);
        employees2.add(emp27);
        employees2.add(emp28);
        employees2.add(emp29);
        List employees3 = new ArrayList();
        employees3.add(emp21);
        employees3.add(emp22);
        employees3.add(emp23);
        employees3.add(emp24);
        List employees4 = new ArrayList();
        employees4.add(emp30);
        employees4.add(emp31);
        employees4.add(emp32);
        employees4.add(emp33);
        employees4.add(emp34);
        employees4.add(emp35);
        employees4.add(emp36);
        employees4.add(emp37);
        employees4.add(emp38);
        employees4.add(emp39);
        employees4.add(emp40);
        employees4.add(emp41);
        employees4.add(emp42);
        employees4.add(emp43);
        employees4.add(emp44);
        employees4.add(emp45);
        employees4.add(emp46);
        employees4.add(emp47);
        employees4.add(emp48);
        employees4.add(emp49);
        employees4.add(emp50);
        List employees5 = new ArrayList();
        employees5.add(emp40);
        employees5.add(emp41);
        employees5.add(emp42);
        employees5.add(emp43);
        employees5.add(emp44);
        employees5.add(emp45);
        employees5.add(emp46);
        employees5.add(emp47);
        employees5.add(emp48);
        employees5.add(emp49);
        employees5.add(emp50);
        employees5.add(emp51);
        employees5.add(emp52);
        employees5.add(emp53);
        employees5.add(emp54);
        employees5.add(emp55);
        employees5.add(emp56);
        employees5.add(emp57);
        employees5.add(emp58);
        employees5.add(emp59);
        employees5.add(emp60);
        Department department1 = new Department(1, "science", employees1);
        Department department2 = new Department(2, "arts", employees2);
        Department department3 = new Department(3, "electronics", employees2);
        Department department4 = new Department(4, "computer science", employees3);
        Department department5 = new Department(5, "r&d", employees4);
        Department department6 = new Department(6, "administration", employees4);
        Department department7 = new Department(7, "telecom", employees5);
        Department department8 = new Department(8, "design", employees5);

        List<Department> departments1 = new ArrayList<>();
        departments1.add(department1);
        departments1.add(department2);
        departments1.add(department3);
        departments1.add(department4);
        departments1.add(department5);
        departments1.add(department6);
        departments1.add(department7);
        departments1.add(department8);

        List<Department> departments2 = new ArrayList<>();
        departments2.add(department2);
        departments2.add(department4);
        departments2.add(department6);
        departments2.add(department8);

        List<Department> departments3 = new ArrayList<>();
        departments3.add(department1);
        departments3.add(department3);
        departments3.add(department5);
        departments3.add(department7);
        departments3.add(department8);

        Company company = new Company(1, "kapit", departments1);
        Company company2 = new Company(2, "eXo", departments2);
        Company company3 = new Company(3, "siemens", departments3);
        Company company4 = new Company(4, "nokia", departments2);
        Company company5 = new Company(5, "microsoft", departments1);
        Company company6 = new Company(6, "google", departments3);
        Company company7 = new Company(7, "amazon", departments3);
        Company company8 = new Company(8, "oracle", departments2);
        Company company9 = new Company(9, "ibm", departments1);
        Company company10 = new Company(10, "yahoo", departments2);

        CompanyDAO companyDAO = new CompanyDAOImpl();
        try {
            System.out.println("...adding companies data");
            companyDAO.addCompany(company);
            companyDAO.addCompany(company2);
            companyDAO.addCompany(company3);
            companyDAO.addCompany(company4);
            companyDAO.addCompany(company5);
            companyDAO.addCompany(company6);
            companyDAO.addCompany(company7);
            companyDAO.addCompany(company8);
            companyDAO.addCompany(company9);
            companyDAO.addCompany(company10);
            System.out.println("...adding data finished");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void addAdminUser() {
        User user = new User("u01", "admin", "admin");
        UserDAO userDAO = new UserDAOImpl();
        try {
            System.out.println("...adding user admin");
            userDAO.addUser(user);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
